version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-footy
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  app:
    build: ./app
    container_name: footy-app
    depends_on:
      - neo4j
    volumes:
      - ./datasets:/app/datasets
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=password
    command: ["sh", "-c", "sleep 20 && python load_to_neo4j.py"]

volumes:
  neo4j_data:
