version: "3.8"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-footy
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - ./datasets:/var/lib/neo4j/import  # 👈 This makes datasets visible to Neo4j
    restart: unless-stopped

  app:
    build: ./app
    container_name: footy-app
    depends_on:
      - neo4j
    volumes:
      - ./datasets:/app/datasets
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=password
    command: ["sh", "-c", "sleep 20 && python load_to_neo4j_bulk.py"]

volumes:
  neo4j_data:
